### ISSUE TITLE
监控-点击启动按钮报错

### ISSUE THREAD

**Issue by lxyzyz111** [solidest/etest_sdk#56]
![捕获](https://user-images.githubusercontent.com/68892238/88631401-aeae4980-d0e4-11ea-8a3d-53809d056e94.PNG)
点击项目这个监控的启动按钮，出现如下报错。

错误提示：测试用例1.lua:11: attempt to perform arithmetic on a nil value (global 'PL')

**Comment by solidest** [comment]
测试脚本编写错误
