### ISSUE TITLE
协议使用Uint15解析器，打包失败

### ISSUE THREAD

**Issue by lijiajie-kiyun** [solidest/etest_sdk#64]
协议中使用Uint15了解析器，打包失败，提示信息如下
![image](https://user-images.githubusercontent.com/60864251/89139317-dd0ea780-d570-11ea-852e-932d84933a78.png)

**Comment by solidest** [comment]
protocol 内全部协议段加起来必须整字节，否则是没办法解析的

**Comment by solidest** [comment]
已经修改提示语为：”协议包长度不是整字节，因此无法打包；整个协议包总长度需要为字节（8bit）的倍数。“
